import type { Meta, StoryObj } from '@storybook/react';
import { GridBaseTest } from './BasicGridTest';
import { CustomBindingData, DynamicDataItem, generateDynamicData } from './data';
import { DataManager, DataUtil, ODataV4Adaptor } from '@syncfusion/react-data';
import App from '../demos/all-feature';
import { EditType, ScrollMode, SelectionMode, WrapMode } from '../src/index';
import HeavyTemplate from './ChartTemplateGrid';
import { BasicColumnValidation, ConditionalTemplate, CustomAutoGeneratedColumns, CustomSort, DeleteConfirmDialogCustomization, DifferentLocaleTwoGrid, EditBasic, ExternalCRUD, FormCustomToolbarEdit, GridLines, HorizontalScrollDropdownTest, LimitSelection, LiveData, Paging, RestrictDecimal, SelectionDatePickerFilter, StateColumnTest, TemplateSwicthing, VisibleStateChange, RemoteDataSample, RowEvent, BasicFiltering, BasicAggregate, CustomData, NullValueSortingHandle, CultureSort, DisableEditColumnDynamically, GettingStartEvents, Overview, CustomAggregate, ExternalButtonSearch, DiacriticsFiltering, SearchOperator, ComplexDataEditing, AggregateEditing, BooleanColumnSingleClickEdit, RowTemplate, TestSample, VirtualScrollingSample } from './TestSample';
const data = generateDynamicData(100);
const cascadingData = [...data];
const meta = {
  title: 'Grid/GridBase',
  component: GridBaseTest,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: 'A fully configurable Grid component with performance comparison capabilities.'
      }
    }
  },
  tags: ['autodocs'],
  argTypes: {
    dataSource: {
      control: 'select',
      options: ['local', 'remote'],
      description: 'Data source type for the grid',
      mapping: {
        local: data,
        remote: new DataManager({
          url: 'https://services.odata.org/V4/Northwind/Northwind.svc/Orders/?$count=true&$skip=0&$top=12',
          adaptor: new ODataV4Adaptor()
        })
      }
    },
    allowKeyboard: {
      control: 'boolean',
      description: 'Enable grid focus navigation'
    },
    allowSearching: {
      control: 'boolean',
      description: 'Enable grid search functionality'
    },
    enableHover: {
      control: 'boolean',
      description: 'Enable hover effect on rows'
    },
    enableRtl: {
      control: 'boolean',
      description: 'Enable right-to-left mode'
    },
    isPrimaryKey: {
      control: 'boolean',
      description: 'Enable primary key column'
    },
    displayAsCheckbox: {
      control: 'boolean',
      description: 'Display checkboxes for boolean type column'
    },
    gridLines: {
      control: 'select',
      options: ['Default', 'None', 'Both', 'Horizontal', 'Vertical'],
      description: 'Grid lines visibility'
    },
    locale: {
      control: 'select',
      options: ['en', 'de', 'fr', 'ar', 'zh'],
      description: 'Grid lines visibility'
    },
    height: {
      control: 'text',
      description: 'Height of the grid'
    },
    width: {
      control: 'text',
      description: 'Width of the grid'
    },
    allowSorting : {
      control: 'boolean',
      description: 'Allow column sorting'
    },
    enableToggle: {
      control: 'boolean',
      description: 'Allow toggle deselection'
    },
    Selectiontype: {
      control: 'select',
      options: ['Single', 'Multiple'],
      description: 'Select the selection type'
    },
    toolbar: {
      control: 'multi-select',
      options: ['Add', 'Edit', 'Delete', 'Update', 'Cancel', 'Search'],
      description: 'Toolbar options supports provided for the grid'
    },
    defaultFreightValue: {
      control: 'number',
      description: 'Default edit value for Freight column'
    },
    allowEdit: {
      control: 'boolean',
      description: 'Allow inline editing'
    },
    ellipsisClipMode: {
      control: 'select',
      options: ['Ellipsis', 'Clip', 'EllipsisWithTooltip'],
      description: 'Overflow content UI appearance of the grid'
    },
    orderDateEllipsisClipMode: {
      control: 'select',
      options: ['Ellipsis', 'Clip', 'EllipsisWithTooltip'],
      description: 'Overflow content UI appearance of the grid'
    },
    editMode: {
      control: 'select',
      options: ['Normal', 'Dialog', 'Batch'],
      description: 'Edit mode for the grid'
    },
    editOnDoubleClick: {
      control: 'boolean',
      description: 'Allow editing on double click'
    },
    allowAdd: {
      control: 'boolean',
      description: 'Allow adding new records'
    },
    allowDelete: {
      control: 'boolean',
      description: 'Allow deleting records'
    },
    newRowPosition: {
      control: 'select',
      description: 'New row position of add row'
    },
    showAddNewRow: {
      control: 'boolean',
      description: 'Show add new row always'
    },
    isSingleClickEdit: {
      control: 'boolean',
      description: 'Allow single click to perform edit'
    },
    allowTextWrap: {
      control: 'boolean',
      description: 'Allow text wrap'
    },
    wrapMode: {
      control: 'select',
      options: [WrapMode.Both, WrapMode.Header, WrapMode.Content],
      description: 'Wrap mode visibility'
    },
    disableHtmlEncode: {
      control: 'boolean',
      description: 'disable html encode'
    },
    enableStickyHeader: {
      control: 'boolean',
      description: 'Enable sticky header'
    },
    enableHtmlSanitizer: {
      control: 'boolean',
      description: 'Enable html sanitizer'
    },
    rowHeight: {
      control: 'text',
      description: 'Height of the grid'
    },
    showOrderID: {
      control: 'boolean',
      description: 'Show Order ID column'
    },
    orderIDWidth: {
      control: 'text',
      description: 'Width of Order ID column'
    },
    orderIDTextAlign: {
      control: 'select',
      options: ['Left', 'Right', 'Center'],
      description: 'Text alignment for Order ID column'
    },
    useOrderIDTemplate: {
      control: 'boolean',
      description: 'Use custom template for Order ID column'
    },
    enableAriaLabel: {
      control: 'boolean',
      description: 'Enable aria-label'
    },
    useOrderIDValueAccessor: {
      control: 'boolean',
      description: 'Use custom value accessor for Order ID column'
    },
    useOrderIDHeaderValueAccessor: {
      control: 'boolean',
      description: 'Use custom header value accessor for Order ID column'
    },
    showOrderDate: {
      control: 'boolean',
      description: 'Show Order Date column'
    },
    orderDateWidth: {
      control: 'text',
      description: 'Width of Order Date column'
    },
    orderDateFormat: {
      control: 'select',
      options: ['dd/MM/yyyy', 'MM/dd/yyyy', 'yyyy-MM-dd', 'dd/MM/yyyy mm:ss', 'MM/dd/yyyy hh:mm tt'],
      description: 'Date format for Order Date column'
    },
    showFreight: {
      control: 'boolean',
      description: 'Show Freight column'
    },
    freightWidth: {
      control: 'text',
      description: 'Width of Freight column'
    },
    freightFormat: {
      control: 'select',
      options: ['C2', 'N2', 'P2', '$#,##0.00'],
      description: 'Number format for Freight column'
    },
    showShipCountry: {
      control: 'boolean',
      description: 'Show Ship Country column'
    },
    useShipCountryTemplate: {
      control: 'boolean',
      description: 'Use custom template for Ship Country column'
    },
    shipCountryWidth: {
      control: 'text',
      description: 'Width of Ship Country column'
    },
    showShipName: {
      control: 'boolean',
      description: 'Show Ship Name column'
    },
    shipNameWidth: {
      control: 'text',
      description: 'Width of Ship Name column'
    },
    showPerformanceMetrics: {
      control: 'boolean',
      description: 'Show performance metrics'
    },
    initialShowSpinner: {
      control: 'boolean',
      description: 'Initially show spinner'
    }
  }
} satisfies Meta<typeof GridBaseTest>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    dataSource: data,
    scrollMode: ScrollMode.Virtual,
    allowSearching: true,
    distinctShipCountryDataSource: DataUtil.distinct(data, 'ShipCountry', true) as DynamicDataItem[],
    enableHover: true,
    enableRtl: false,
    gridLines: 'Default',
    height: 400,
    Selectiontype: 'Multiple',
    // enableToggle: true,
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: true,
    allowSorting: true,
    allowFiltering: true,
    allowEdit: false,
    editMode: 'Normal',
    editOnDoubleClick: true,
    allowAdd: false,
    allowDelete: false,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: true,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    useOrderIDTemplate: false,
    enableAriaLabel: true,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'M/d/yyyy',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: true,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false
  }
};

export const MinimalGrid: Story = {
  args: {
    dataSource: data.slice(0, 10),
    enableHover: true,
    enableRtl: false,
    gridLines: 'Horizontal',
    height: 300,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowSorting: false,
    allowFiltering: false,
    allowEdit: false,
    editMode: 'Normal',
    editOnDoubleClick: true,
    allowAdd: false,
    allowDelete: false,
    allowPaging: false,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: true,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Left',
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'dd/MM/yyyy',
    showFreight: false,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: false,
    shipCountryWidth: '130',
    showShipName: false,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false
  }
};

export const TemplatedColumns: Story = {
  args: {
    dataSource: data.slice(0, 20),
    distinctShipCountryDataSource: DataUtil.distinct(data, 'ShipCountry', true) as DynamicDataItem[],
    enableHover: true,
    enableRtl: false,
    gridLines: 'Both',
    height: 400,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: false,
    allowSorting: true,
    allowFiltering: false,
    allowEdit: false,
    editMode: 'Normal',
    editOnDoubleClick: true,
    allowAdd: false,
    allowDelete: false,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: false,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Center',
    useOrderIDTemplate: true,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'dd/MM/yyyy mm:ss',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    useShipCountryTemplate: true,
    shipCountryWidth: '130',
    showShipName: true,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false
  }
};

export const CustomAccessors: Story = {
  args: {
    dataSource: data.slice(0, 20),
    enableHover: true,
    enableRtl: false,
    gridLines: 'Both',
    height: 400,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: false,
    allowSorting: true,
    allowFiltering: false,
    allowEdit: false,
    editMode: 'Normal',
    editOnDoubleClick: true,
    allowAdd: false,
    allowDelete: false,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: true,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: true,
    useOrderIDHeaderValueAccessor: true,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'dd/MM/yyyy mm:ss',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: true,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false
  }
};

export const FullyCustomized: Story = {
  args: {
    dataSource: data.slice(0, 20),
    enableHover: true,
    enableRtl: false,
    gridLines: 'Both',
    height: 400,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: false,
    allowSorting: true,
    allowFiltering: true,
    allowEdit: false,
    editMode: 'Normal',
    editOnDoubleClick: true,
    allowAdd: false,
    allowDelete: false,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: false,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Center',
    useOrderIDTemplate: true,
    useOrderIDValueAccessor: true,
    useOrderIDHeaderValueAccessor: true,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'dd/MM/yyyy mm:ss',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: true,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false
  }
};

export const RTLMode: Story = {
  args: {
    dataSource: data.slice(0, 30),
    enableHover: true,
    enableRtl: true,
    gridLines: 'Default',
    height: 400,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: true,
    allowSorting: true,
    allowFiltering: true,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: true,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'dd/MM/yyyy',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: true,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false
  }
};

export const RemoteData: Story = {
  args: {
    dataSource: new DataManager({
      url: 'https://services.odata.org/V4/Northwind/Northwind.svc/Orders',
      adaptor: new ODataV4Adaptor(),
      // enableCache: true
    }),
    scrollMode: ScrollMode.Virtual,
    virtualizationSettings: {enableCache: false},
    enableHover: true,
    enableRtl: false,
    gridLines: 'Default',
    height: 400,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: true,
    allowSorting: true,
    allowFiltering: true,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: true,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: true,
    orderDateWidth: '130',
    orderDateFormat: 'dd/MM/yyyy mm:ss',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: true,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: true
  }
};

export const CustomBinding: Story = {
  args: {
    dataSource: {
      result: CustomBindingData.slice(0, 12),
      count: CustomBindingData.length,
      aggregates: {
        'Freight - sum': 555,
        'ShipCountry - count': 666
      } as any
    },
    allowPaging: true,
    enableHover: true,
    enableRtl: false,
    gridLines: 'Default',
    height: 700,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowSorting: true,
    allowFiltering: true,
    allowEdit: true,
    editMode: 'Normal',
    editOnDoubleClick: true,
    allowAdd: true,
    allowDelete: true,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: true,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: false,
    orderDateWidth: '130',
    orderDateFormat: 'yMd',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: false,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false,
    toolbar: ['Add', 'Edit', 'Cancel', 'Update', 'Delete', 'Search'],
    isPrimaryKey: true,
    customBindingAggregates: true
  }
};

export const Aggregates: Story = {
  args: {
    dataSource: data,
    enableHover: true,
    enableRtl: false,
    gridLines: 'Both',
    height: 500,
    Selectiontype: 'Single',
    allowTextWrap: true,
    wrapMode: "Both",
    rowHeight: 50,
    width: '100%',
    allowPaging: true,
    allowSorting: true,
    allowFiltering: true,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: false,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    showOrderDate: false,
    orderDateWidth: '130',
    orderDateFormat: 'yMd',
    showFreight: true,
    freightWidth: '120',
    freightFormat: 'C2',
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: false,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false,
    showAggregates: true,
    showSalary: true,
    showCost: true
  }
};

export const NormalEditingWithToolbar: Story = {
  args: {
    dataSource: data,
    enableHover: true,
    enableRtl: false,
    gridLines: 'Both',
    height: 700,
    enableToggle: true,
    Selectiontype: SelectionMode.Multiple,
    isPrimaryKey: true,
    allowEdit: true,
    defaultFreightValue: 120,
    allowDelete: true,
    confirmOnDelete: false,
    allowAdd: true,
    toolbar: ['Add', 'Edit', 'Search', 'Cancel', 'Update', 'Delete'],
    editOnDoubleClick: true,
    allowTextWrap: false,
    wrapMode: "Both",
    width: '100%',
    allowPaging: true,
    orderDateEllipsisClipMode: 'EllipsisWithTooltip',
    allowSorting: true,
    allowFiltering: true,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: false,
    showOrderID: false,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    enableAriaLabel: false,
    useOrderIDTemplate: true,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    activeEditType: EditType.CheckBox,
    orderDateEditType: EditType.DatePicker,
    shipCountryEditType: EditType.DropDownList,
    // _freightEditType: EditType.NumericTextBox,
    cascadingData: cascadingData,
    showOrderDate: true,
    orderDateWidth: '90',
    orderDateFormat: 'd/M/yyyy',
    showFreight: true,
    freightWidth: '120',
    freightFormat: {format: 'C2'},
    showShipCountry: true,
    shipCountryWidth: '130',
    showShipName: true,
    showAddNewRow: true,
    isSingleClickEdit: false,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false,
    showAggregates: true,
    showSalary: true,
    showCost: true
  }
};

export const CommandColumnEditing: Story = {
  args: {
    dataSource: data,
    enableHover: true,
    enableRtl: false,
    gridLines: 'Both',
    height: 600,
    enableToggle: true,
    Selectiontype: SelectionMode.Multiple,
    isPrimaryKey: true,
    allowEdit: true,
    defaultFreightValue: 120,
    allowDelete: true,
    confirmOnDelete: false,
    allowAdd: true,
    toolbar: ['Add'],
    editOnDoubleClick: true,
    allowTextWrap: false,
    wrapMode: "Both",
    width: '100%',
    allowPaging: true,
    orderDateEllipsisClipMode: 'EllipsisWithTooltip',
    allowSorting: true,
    allowFiltering: true,
    disableHtmlEncode: true,
    enableStickyHeader: true,
    enableHtmlSanitizer: false,
    showOrderID: true,
    orderIDWidth: '180',
    orderIDTextAlign: 'Right',
    enableAriaLabel: false,
    useOrderIDTemplate: false,
    useOrderIDValueAccessor: false,
    useOrderIDHeaderValueAccessor: false,
    activeEditType: EditType.CheckBox,
    orderDateEditType: EditType.DatePicker,
    shipCountryEditType: EditType.DropDownList,
    // _freightEditType: EditType.NumericTextBox,
    cascadingData: cascadingData,
    showOrderDate: true,
    orderDateWidth: '90',
    orderDateFormat: 'M/d/yyyy',
    showFreight: true,
    freightWidth: '120',
    freightFormat: {format: 'C2'},
    showShipCountry: false,
    shipCountryWidth: '130',
    showShipName: true,
    showAddNewRow: false,
    isSingleClickEdit: false,
    shipNameWidth: '130',
    showPerformanceMetrics: true,
    initialShowSpinner: false,
    showAggregates: true,
    showSalary: false,
    showCost: false,
    showCommandEditing: true
  }
};

export const AllFeature: Story = {
  args: {
    // Reusing props from Default story
    ...Default.args
  },
  render: () => {
    return <div id="feature-matrix"><App/></div>
  }
};

export const DOMVirtualizationSample: Story = {
  args: {
    ...Default.args
  },
  render: (args) => {
    // return <HorizontalScrollDropdownTest recordCount={1000} />
    // return <div style={{marginTop: '100px'}}><StateColumnTest /></div>
    // return <div style={{marginTop: '100px'}}><ExternalCRUD /></div>
    // return <div style={{marginTop: '100px'}}><DeleteConfirmDialogCustomization /></div>
    // return <div style={{marginTop: '100px'}}><BasicColumnValidation /></div>
    // return <div style={{marginTop: '100px'}}><FormCustomToolbarEdit /></div>
    // return <div style={{marginTop: '100px'}}><RestrictDecimal /></div>
    // return <div style={{marginTop: '100px'}}><CustomAutoGeneratedColumns /></div>
    // return <div style={{marginTop: '100px'}}><GridLines /></div>
    // return <div style={{marginTop: '100px'}}><TemplateSwicthing /></div>
    // return <div style={{marginTop: '100px'}}><VisibleStateChange /></div>
    // return <div style={{marginTop: '100px'}}><EditBasic /></div>
    // return <div style={{marginTop: '100px'}}><LimitSelection /></div>
    // return <div style={{marginTop: '100px'}}><CustomSort /></div>
    // return <div style={{marginTop: '100px'}}><NullValueSortingHandle /></div>
    // return <div style={{marginTop: '100px'}}><CultureSort /></div>
    // return <div style={{marginTop: '100px'}}><DifferentLocaleTwoGrid /></div>
    // return <div style={{marginTop: '100px'}}><ConditionalTemplate /></div>
    // return <div style={{marginTop: '100px'}}><LiveData /></div>
    // return <div style={{marginTop: '100px'}}><Paging /></div>
    // return <div style={{marginTop: '100px'}}><SelectionDatePickerFilter /></div>
    // return <div style={{marginTop: '100px'}}><RemoteDataSample /></div>
    // return <div style={{marginTop: '100px'}}><RowEvent /></div>
    // return <div style={{marginTop: '100px'}}><BasicFiltering /></div>
    // return <div style={{marginTop: '100px'}}><BasicAggregate /></div>
    // return <div style={{marginTop: '100px'}}><CustomData /></div>
    // return <div style={{marginTop: '100px'}}><DisableEditColumnDynamically /></div>
    // return <div style={{marginTop: '100px'}}><GettingStartEvents /></div>
    // return <div style={{marginTop: '100px'}}><Overview /></div>
    // return <div style={{marginTop: '100px'}}><CustomAggregate /></div>
    // return <div style={{marginTop: '100px'}}><ExternalButtonSearch /></div>
    // return <div style={{marginTop: '100px'}}><DiacriticsFiltering /></div>
    // return <div style={{marginTop: '100px'}}><SearchOperator /></div>
    // return <div style={{marginTop: '100px'}}><ComplexDataEditing /></div>
    // return <div style={{marginTop: '100px'}}><AggregateEditing /></div>
    // return <div style={{marginTop: '100px'}}><BooleanColumnSingleClickEdit /></div>
    return <div><TestSample /></div>
    // return <div style={{marginTop: '100px'}}><RowTemplate /></div>
  }
};

export const VirtualScrollSample: Story = {
  args: {
    ...Default.args
  },
  render: (args) => {
    return <div><VirtualScrollingSample /></div>
  }
};

// export const HeavyTemplateFeature: Story = {
//   args: {
//     // Reusing props from Default story
//     ...Default.args
//   },
//   render: () => {
//     return <div id="heavy-template"><HeavyTemplate/></div>
//   }
// };
